gcloud:
    project-id: 'scalability-223413'
    subscription-name: 'conversion'

aws:
    dynamodb:
        name: 'dynamodb'
        table: 'video'
        region: 'eu-west-3'
    s3:
        name: 'edu.esipe.i3.ezipflix'
        region: 'eu-west-3'